theme: jekyll-theme-minimal
title: Gregor Rot
description: My work website hosted on GitHub, with description of projects I am working on at the moment.<br><a href="www.twitter.com/gregor_rot>Twitter</a><br>
